# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: RobotTests_WF
on:
  workflow_dispatch:
 
   inputs:          
        Execution_Environment:
          description: 'Execution Environment'
          default: 'NON-PROD'
          required: true
          type: string

jobs:
  buildrobotframework:

    runs-on: self-hosted

    env:
        #Application Username(s) and Password(s)
        APP_USERNAME: ${{ secrets.APP_USERNAME }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        REG_USERNAME: ${{ secrets.REG_USERNAME }}
        REG_PASSWORD: ${{ secrets.REG_PASSWORD }}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: mainframe-robot-framework

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        #robot ./Tests/soecs.robot
        robot --variable APP_PASSWORD:${APP_PASSWORD} --variable REG_PASSWORD:${REG_PASSWORD} --variable APP_USERNAME:${APP_USERNAME} --variable REGION:imsc --variable REG_USERNAME:${REG_USERNAME} ./Tests/CRIS.robot
